# Generated by Django 4.2.6 on 2023-10-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_category_client_detsale_product_sale_delete_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='decs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
