# Generated by Django 4.2.6 on 2023-10-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_category_decs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='decs',
            new_name='desc',
        ),
    ]
